FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt . 

RUN apt-get update && apt-get install -y git && apt-get clean
RUN pip install --no-cache-dir -r requirements.txt

COPY --chmod=755 ejecutar.sh .
COPY proyecto_dbt ./proyecto_dbt
RUN sed -i 's/\r$//' ejecutar.sh

CMD ["./ejecutar.sh"]