FROM python:3.12-slim

WORKDIR /app

COPY CALIDAD_AIRE_HORARIOS20251013.csv .
COPY requirements.txt . 
COPY ingestionMAD.py .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "ingestionMAD.py"]