FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
COPY ingestionMAD.py .
COPY ingestionBCN.py .
RUN pip install -r requirements.txt

COPY --chmod=755 ingestion.sh .
RUN sed -i 's/\r$//' ingestion.sh

CMD ["./ingestion.sh"]