CREATE TABLE IF NOT EXISTS calidad_aire_madrid (
    id SERIAL PRIMARY KEY,
    MUNICIPIO INT, 
    ESTACION VARCHAR(10),     
    MAGNITUD INT,
    PUNTO_MUESTREO VARCHAR(20),
    ANO INT,
    MES INT,
    DIA INT,
    HORA INT,
    VALOR NUMERIC,
    VALIDACION CHAR(1)
)