CREATE TABLE IF NOT EXISTS calidad_aire (
    id SERIAL PRIMARY KEY,
    MUNICIPIO INT, 
    ESTACION VARCHAR(100),     
    MAGNITUD VARCHAR(10),
    PUNTO_MUESTREO VARCHAR(20),
    ANO INT,
    MES INT,
    DIA INT,
    HORA INT,
    VALOR NUMERIC,
    VALIDACION CHAR(1),
    LAT NUMERIC,
    LON NUMERIC
)