models:
  # 1. MODELO STAGING (Limpieza)
  - name: stg_CalidadAire_Mad
    description: "Limpieza básica y renombramiento de columnas"

  # 2. MODELO INTERMEDIATE 
  - name: int_CalidadAire_Mad
    description: "Tabla enriquecida con nombres reales y no solo codigos, fechas unificadas"
    columns:
      - name: id
        description: "Clave primaria"
        tests:
          - unique
          - not_null
      - name: municipio
        description: "Nombre del municipio (Madrid)"
      - name: estacion
        description: "Nombre real de la estación de medición"
      - name: indicador_contaminante
        description: "Tipo de contaminante (NO2, PM2.5, etc)"
      - name: fecha_hora
        description: "Fecha y hora exacta de la medición"
        tests:
          - not_null
      - name: datos_disponibles
        description: "Booleano: True si el dato esta disponible según la API"