sources:
  - name: aire
    database: dataproject1db  # O el nombre de tu BD real
    schema: public
    tables:
      - name: calidad_aire
        description: "Datos de calidad del aireobtenidos de la API pública"
        config:
          loaded_at_field: fecha_carga
          freshness:
          warn_after: {count: 2, period: hour} # Avísame si el dato tiene > 2 horas
          error_after: {count: 10, period: hour} # Falla si tiene > 10 horas

          